import React from 'react';
import { BarChart, Bar, Cell, PieChart, Pie, XAxis, YAxis, Tooltip, ResponsiveContainer } from 'recharts';
import { Sparkles, BarChart3, AlertTriangle, Scale, CalendarRange, BrainCircuit } from 'lucide-react';
import { DepartmentReadiness, WorkloadSignal } from '../types';

interface ManagerInsightsProps {
  departments: DepartmentReadiness[];
  workloadSignals: WorkloadSignal[];
}

export const ManagerInsightsView: React.FC<ManagerInsightsProps> = ({
  departments,
  workloadSignals
}) => {
  
  // Format data for BarChart (Department scores)
  const barData = departments.map(d => ({
    name: d.name.replace('Information Technology', 'IT').replace('Quality Management', 'Quality'),
    score: d.score,
    isLow: d.score < 70
  }));

  // Pie chart readiness distribution data
  // Ready: 2, On Track: 1, At Risk: 1, Not Ready: 2
  const pieData = [
    { name: 'Ready (≥85%)', value: 2, color: 'var(--accent-green)' },
    { name: 'On Track (75-84%)', value: 1, color: 'var(--accent-indigo)' },
    { name: 'At Risk (70-74%)', value: 1, color: 'var(--accent-amber)' },
    { name: 'Not Ready (<70%)', value: 2, color: 'var(--accent-red)' }
  ];

  return (
    <div>
      {/* Top section: Executive Briefing */}
      <div className="card executive-brief" id="executive-briefing-card">
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px', color: 'var(--accent-indigo)', fontSize: '11px', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: '8px' }}>
          <BrainCircuit size={14} />
          AI-generated executive briefing
        </div>
        <p style={{ fontSize: '14px', lineHeight: '1.7', color: 'var(--text-primary)', fontWeight: 500 }}>
          Organisational readiness stands at <strong>76%</strong>, representing a 4-point improvement over the prior period. Two departments — Operations and Procurement — remain below the certification threshold of 70% and carry open major nonconformities that pose direct audit failure risk. Immediate management attention is required for both. Four of six process owners have completed required training. The upcoming external audit in 47 days creates a critical window for corrective action.
        </p>
        <div className="brief-metadata">
          <Sparkles size={13} />
          Generated by Manager Insights Agent · Fabric IQ + Work IQ · 2 min ago
        </div>
      </div>

      {/* Middle: 2-column chart row */}
      <div className="two-col-grid-50-50">
        {/* Left: Bar Chart */}
        <div className="card" style={{ display: 'flex', flexDirection: 'column' }}>
          <h3 className="section-title">
            <BarChart3 size={15} style={{ color: 'var(--accent-teal)' }} />
            Department Score Analysis
          </h3>
          <p className="section-subtitle">Readiness scores against core ISO threshold (70%)</p>

          <div style={{ flex: 1, minHeight: '220px', width: '100%' }}>
            <ResponsiveContainer width="100%" height={220}>
              <BarChart data={barData} margin={{ top: 10, right: 10, left: -25, bottom: 5 }}>
                <XAxis
                  dataKey="name"
                  stroke="var(--text-secondary)"
                  fontSize={10.5}
                  tickLine={false}
                />
                <YAxis
                  domain={[0, 100]}
                  stroke="var(--text-secondary)"
                  fontSize={10.5}
                  tickLine={false}
                  tickFormatter={(val) => `${val}%`}
                />
                <Tooltip
                  contentStyle={{
                    backgroundColor: 'var(--bg-secondary)',
                    borderColor: 'var(--border)',
                    borderRadius: '8px',
                    color: 'var(--text-primary)',
                    fontFamily: 'var(--font-sans)',
                    fontSize: '12px'
                  }}
                  formatter={(val) => [`${val}% Score`]}
                />
                <Bar dataKey="score">
                  {barData.map((entry, index) => (
                    <Cell
                      key={`cell-${index}`}
                      fill={entry.isLow ? 'var(--accent-red)' : 'var(--accent-teal)'}
                    />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Right: Pie Donut Chart */}
        <div className="card" style={{ display: 'flex', flexDirection: 'column' }}>
          <h3 className="section-title">
            <Scale size={15} style={{ color: 'var(--accent-indigo)' }} />
            Compliance Distribution
          </h3>
          <p className="section-subtitle">Department status segments (6 total sectors)</p>

          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '20px', flex: 1, minHeight: '220px' }}>
            {/* Pie Chart SVG representation */}
            <div style={{ width: '150px', height: '150px' }}>
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie
                    data={pieData}
                    cx="50%"
                    cy="50%"
                    innerRadius={50}
                    outerRadius={70}
                    paddingAngle={3}
                    dataKey="value"
                  >
                    {pieData.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.color} />
                    ))}
                  </Pie>
                  <Tooltip
                    contentStyle={{
                      backgroundColor: 'var(--bg-secondary)',
                      borderColor: 'var(--border)',
                      borderRadius: '8px',
                      color: 'var(--text-primary)',
                      fontFamily: 'var(--font-sans)',
                      fontSize: '11px'
                    }}
                    formatter={(val) => [`${val} Depts`]}
                  />
                </PieChart>
              </ResponsiveContainer>
            </div>

            {/* Labels Custom list */}
            <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
              {pieData.map((item, idx) => (
                <div key={idx} style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                  <div style={{ width: '8px', height: '8px', borderRadius: '50%', backgroundColor: item.color }} />
                  <span style={{ fontSize: '12px', color: 'var(--text-secondary)' }}>
                    {item.name}: <strong>{item.value}</strong>
                  </span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* Bottom: Capacity & Workload table */}
      <div className="card">
        <h3 className="section-title">
          <CalendarRange size={15} style={{ color: 'var(--accent-amber)' }} />
          Foundry Work IQ — Cognitive Workload Signals
        </h3>
        <p className="section-subtitle">Process owner baseline and allocated weekly ISO study availability</p>

        <div style={{ overflowX: 'auto' }}>
          <table className="custom-table" id="workload-table">
            <thead>
              <tr>
                <th style={{ paddingLeft: '8px' }}>Process Owner</th>
                <th>Role</th>
                <th>Workload Capacity</th>
                <th>Meeting Hours</th>
                <th>Focus Hours</th>
                <th>Available Study Window</th>
              </tr>
            </thead>
            <tbody>
              {workloadSignals.map((signal) => {
                let capBadge = 'badge-green';
                let capText = 'Available';

                if (signal.capacity === 'overloaded') {
                  capBadge = 'badge-red';
                  capText = 'OVERLOADED';
                } else if (signal.capacity === 'constrained') {
                  capBadge = 'badge-red';
                  capText = 'Constrained';
                } else if (signal.capacity === 'limited') {
                  capBadge = 'badge-amber';
                  capText = 'Limited';
                }

                return (
                  <tr key={signal.id} style={{ backgroundColor: signal.capacity === 'overloaded' ? 'rgba(239, 68, 68, 0.01)' : 'transparent' }}>
                    <td style={{ fontWeight: 600, paddingLeft: '8px', fontFamily: 'var(--font-mono)' }}>{signal.owner}</td>
                    <td style={{ color: 'var(--text-secondary)' }}>{signal.role}</td>
                    <td>
                      <span className={`badge ${capBadge}`} style={{ fontSize: '11px' }}>
                        {capText}
                      </span>
                    </td>
                    <td style={{ fontWeight: 500 }}>{signal.meetingHrs} hrs/wk</td>
                    <td style={{ color: 'var(--text-secondary)' }}>{signal.focusHrs} hrs/wk</td>
                    <td style={{ fontWeight: 600, color: 'var(--accent-teal)' }}>{signal.learningSlot}</td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
